name: Full Stack CI
run-name: ${{github.actor}} triggered CI pipeline 
on: [push]

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Within the compilation of the image, we run cargo test,
    # if any of the tests fail, the process fails
    - name: docker compose build, test, deploy
      run: docker compose up -d --build
  
    - name: Tear down
      if: always()
      run: docker compose down
    



